// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYgzJ9gtUlwdIov09HKQc3V0e0kXqmbaQ',
    appId: '1:1095002141430:web:1968836c085b00228eb2d7',
    messagingSenderId: '1095002141430',
    projectId: 'taskist-2ff1c',
    authDomain: 'taskist-2ff1c.firebaseapp.com',
    storageBucket: 'taskist-2ff1c.appspot.com',
    measurementId: 'G-F918P7Q17M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_MvSXL54v-d4EeU0EKzwEEqhm9ahLHuE',
    appId: '1:1095002141430:android:d60c21938c5df14a8eb2d7',
    messagingSenderId: '1095002141430',
    projectId: 'taskist-2ff1c',
    storageBucket: 'taskist-2ff1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4g2x37DqLqcf73njiQOtNbOwydATVwLA',
    appId: '1:1095002141430:ios:bad0efc771c829e08eb2d7',
    messagingSenderId: '1095002141430',
    projectId: 'taskist-2ff1c',
    storageBucket: 'taskist-2ff1c.appspot.com',
    iosClientId: '1095002141430-2077o1r44tu33t79ln4u974fv43c0gbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskistClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4g2x37DqLqcf73njiQOtNbOwydATVwLA',
    appId: '1:1095002141430:ios:bad0efc771c829e08eb2d7',
    messagingSenderId: '1095002141430',
    projectId: 'taskist-2ff1c',
    storageBucket: 'taskist-2ff1c.appspot.com',
    iosClientId: '1095002141430-2077o1r44tu33t79ln4u974fv43c0gbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskistClone',
  );
}
